name: Cron

on:
  schedule:
    - cron: 0 2 * * *

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [15.x]
        go-version: [1.16.x]

    steps:
      - uses: actions/checkout@master
        with:
          ref: src
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: npm install, build
        run: |
          npm install
          sed -i "s/LIVERE_UID/$LIVERE_UID/g" themes/next/_config.yml
          npm run generate
          go mod tidy
          go run replace-image.go
          # node relace-image.js
        env:
          YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
          LIVERE_UID: ${{ secrets.LIVERE_UID }}
          OSS_ACCESS_KEY: ${{ secrets.OSS_ACCESS_KEY }}
          OSS_SECRET_KEY: ${{ secrets.OSS_SECRET_KEY }}
          ALI_ACCOUNT_ID: ${{ secrets.ALI_ACCOUNT_ID }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
      - name: Deploy to Staging server
        run: |
          sshpass -p $SSH_PASS scp -o StrictHostKeyChecking=no -r $SOURCE $REMOTE_USER@$REMOTE_HOST:$TARGET
        env:
          SSH_PASS: ${{ secrets.SSH_PASS }}
          ARGS: "-aru"
          SOURCE: "public/*"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/usr/share/nginx/html/"
      - name: Commit files
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: src
        continue-on-error: true
