name: Node CI

on: [push, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@master
        with:
          ref: src
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build
        run: |
          npm install
          sed -i "s/LIVERE_UID/$LIVERE_UID/g" themes/next/_config.yml
          npm run generate
          cp CNAME ./public/CNAME
        env:
          CI: true
          YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
          LIVERE_UID: ${{ secrets.LIVERE_UID }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
